# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shubham Kamboj
user_description: Hi, there myself Shubham Kamboj, from India, currently i am pursuing B.tech in CSE from Indian Institute of Information Technology, Una. I like computer programming, currently i am developing my own websites.
user_title: Computer Programmer
email: iiitu16118@gmail.com
twitter_username: shkamboj
github_username:  shkamboj
gplus_username:   

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
